create table audio
(
    id               bigint generated by default as identity
        primary key,
    audio_path       varchar(255)                not null,
    content_type     varchar(100)                not null,
    cover_path       varchar(255),
    created_at       timestamp(6) with time zone not null,
    description      text,
    duration_seconds integer                     not null,
    is_premium       boolean                     not null,
    owner_id         bigint                      not null,
    search_vector    tsvector,
    title            varchar(255)                not null
);

alter table audio
    owner to audio_user;

create table library_item
(
    id       bigint generated by default as identity
        primary key,
    saved_at timestamp(6) with time zone,
    user_id  bigint not null,
    audio_id bigint not null
        constraint fkvjlr7f4yg7gt345mtokeutye
            references audio,
    constraint uk358l1u1y93ptvob95pda56157
        unique (user_id, audio_id)
);

alter table library_item
    owner to audio_user;

create table listening_progress
(
    id               bigint                      not null
        primary key,
    audio_id         bigint                      not null,
    position_seconds integer                     not null,
    updated_at       timestamp(6) with time zone not null,
    user_id          bigint                      not null,
    constraint uq_progress_user_audio
        unique (user_id, audio_id)
);

alter table listening_progress
    owner to audio_user;

create table users
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6) with time zone,
    email         varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    password_hash varchar(255) not null,
    role          varchar(255)
        constraint users_role_check
            check ((role)::text = ANY
        ((ARRAY ['FREE'::character varying, 'PREMIUM'::character varying, 'ADMIN'::character varying])::text[]))
    );

alter table users
    owner to audio_user;

create table refresh_tokens
(
    id         bigint generated by default as identity
        primary key,
    expires_at timestamp(6) with time zone not null,
    token      varchar(255)                not null
        constraint ukghpmfn23vmxfu3spu3lfg4r2d
            unique,
    user_id    bigint                      not null
        constraint fk1lih5y2npsf8u5o3vhdb9y0os
            references users
);

alter table refresh_tokens
    owner to audio_user;

